// AUTO-GENERATED by frontend/scripts/gen-quiz-counts.mjs — DO NOT EDIT.
/**
 * @file 분야별 난이도 문항 수 (auto-generated)
 * @domain quiz
 * @layer data
 * @related frontend/scripts/gen-quiz-counts.mjs, src/data/quiz/types.ts, src/data/quiz/counts.ts
 */
import { QuizCategory } from './types';
import type { QuizDifficulty } from './types';

/** 분야별 난이도 문항 수 (gen-quiz-counts.mjs 자동 생성). */
export const QUESTION_COUNTS = {
  [QuizCategory.DATA_STRUCTURE]: { EASY: 16, MEDIUM: 17, HARD: 17 },
  [QuizCategory.ALGORITHM]: { EASY: 16, MEDIUM: 17, HARD: 17 },
  [QuizCategory.NETWORK]: { EASY: 16, MEDIUM: 17, HARD: 17 },
  [QuizCategory.OS]: { EASY: 16, MEDIUM: 17, HARD: 17 },
  [QuizCategory.DATABASE]: { EASY: 16, MEDIUM: 17, HARD: 17 },
  [QuizCategory.COMPUTER_ARCHITECTURE]: { EASY: 7, MEDIUM: 7, HARD: 6 },
  [QuizCategory.DESIGN_PATTERN]: { EASY: 7, MEDIUM: 7, HARD: 6 },
  [QuizCategory.WEB]: { EASY: 7, MEDIUM: 7, HARD: 6 },
  [QuizCategory.SECURITY]: { EASY: 7, MEDIUM: 7, HARD: 6 },
  [QuizCategory.AI]: { EASY: 7, MEDIUM: 7, HARD: 6 },
} as const satisfies Record<QuizCategory, Record<QuizDifficulty, number>>;
