---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-secret
  namespace: algosu
spec:
  encryptedData:
    root-password: AgBpoAmA3YbpBbFveJMkmyJ1QuZfYS34flUzQh7+5s4L9+Is5a/EBZT06AJPic6Lp+keA7VP2Eg7sTAWg+1o4Oz87PeOja6X0xRQXX8cFEGil0nAv0bIxwO6c2ZnjNsmiUJZiQLDiqWEfXOyuKMlTGGmcQQrrvrdgg6KUj6ZX+JJ4tyIwcn2eck6DVx+nAnhaapJCusSdP8NSofO5ZPzd+5t15pX+peZnQ87FrUQBtaD2HRGZUDUwMuObDFv58fWIYbLyskSrwJpWRirK8uBHTN3kAI4Vk0pve7lwFB1TKgDDdMCkNqvH6zytk6uLyxuXNhhh8pdnH0/qNQx4TCNfjTTENGthpz6qQTvMZyw29yhuHlcLtJzb6M7zEdE4jmJtq0/I5t/8AovfblADXUXQt0uXKHwxmZp+srvPdSmcyJtrcI3wZqHguzGKRe3o5r6hm16FGgZmQ1GZG6Y0MnB+08jyKx+u94DOjl6dlLoeDLi25/l2k8TQFckjIUiijxbK8KpoGMKHuLYhylnhUY6kE1wQCAJgkEFY4hRkl6BmxQZ7JjtLrqcyOPLmc5VCDN0mc0F1E6//pD/J0Tk0WAcVIqJqi9OvJPZotpcy0h0BUfXDUMCnusrSqkGr+7o1W0I6t5oa2C+0X+I1F5HhJK+q3YGERA1ex9VLSs/c27JQRnOtnduPvsDlWxcZEHTekeLEn07Q1dEbU5tCE9Oaf4n+jGQi8fcsVkDEVuSNdRvShyxEw==
    root-user: AgBAVCdtfMagmZfBbE0oqKTm7yn/MEfqEGwgv1jLUcxRBwTDBF49A01ThoITA0UDXZ10PSirDHpuXeDmGbyGAkAC7CVU9ozkiLJL5UIJOA84SNJXWnjgT6oz/S0FS9GxSAsmk3kKZrJffrA3vBrfXP1LNneMR9Eshr1g18WRYW0sUgFBaGAVlWFeBlVAT37iD07/XO+6FzgZLf5CnEHhgE3aIenyjnNO4Z5yy5qrxQkkSk4xhvtaOt1H1dFccfA7adpAR3JrMTJfN2jh6xkZPZKH9IvFrDcNpW15zitAiFIsrKheFySdJ3qxe6hf8DCIcGwLvKCCzSEyygLVsXxVU9z2bPXJ6hQ9U4bUp6RvhXwxinTHDnomwjlDb6hXc7gLNT53ZrJcLTtAUMUHyPTE5KTIaeVQ3tHZDLi4TH21FH28C1uudji0f3lS5kKrbfEGi8RmSTwOfJuXa3oSq0RTVN1R1cR2iEF4GER4ace/J0X4YTB+fLOcEuTcDHMMRDq8kr1VslH8TdX/5LKv/9YIV3qwc4IZFpJXMpsLAMSmblw8vPdaJrDvFJ3FujFYeirSPMDz9YXijHJTY+lHeGKmQonSyLjF6RVo2M0bIQhh0a2kgUhisk4/hS/BaEmEIw/Lx1J/k0uvST+Aw1/akCf6DJNJ64cVzYNJvJNz3jC7MQm9rrntynvJ1eRHIrC60ejnHBOnjGOGTxUsf9IM73s=
  template:
    metadata:
      name: postgres-secret
      namespace: algosu
