---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-problem-secret
  namespace: algosu
spec:
  encryptedData:
    password: AgAAHzl0w1YQOYmVpswSo6whLdUtpETuFWVG3ZjOMAij+dBjdb9oe8jTcuuQ5lPS3T8AhtOSPFlaWRdDkByhIQAicYvtF/FMCVbvIo0tKqY6y1JAVxhCqRYyCSNs8Pj5OnaTkoTHrzxtahJEH29NPth5HNIiE5pgjFmj/sAhAHoDOc2Y0rMS/rPC6JBV9mAwJnXSWqBKwX1E7lTbjU3EuvwV+QiWAldBekFpJ8cKmLJhsJKh/YdjnZliFI2A5KvD8IkM1LiDuFhArJQ1ANXYqVBd9JoD90/Go72MhzJ2aPw0KA5qKglyH3XWAf2rTYHpuSNtJT2CT0lL8Bqv9UpWv76YKYIrVMhFlmlcJyMWay4XwULY/8UZln5O5F8B3PZv7tZVUUl55WWvba8vWJFMOuM4tXoDg60FZlXpXZHI66o6P2i5BXI1hfvS0Ot36Sz8YiH7HiwS2uEhSEdG/XyWync+wdBjecd9xrg+aVupHfzjVF0eGFMmdiXAfhUbwGDBG1+HZ8dhdwJb2UsUXiwNKWpEbRYY8grAMbija3HgfU7+xxMvUIpP+1iaDUc3MA8jbkzmalNuYQk/2rXac7IDy6E4GJETg0oN1OC5ap2OKfN+P4LuFRRTr8mVbUHHqds3IH0piIxtsbbq7on6lNxz08SsfbwCa4yhLrtlU9kQIcn4ogNgU54qAXshyEgz7gWzBcJnTB/ASdmi6MEQ9sq47QeOqSotdlgs2ciTu4iBrMGqKw==
  template:
    metadata:
      name: postgres-problem-secret
      namespace: algosu
