---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: monitoring-secrets
  namespace: algosu
spec:
  encryptedData:
    GRAFANA_ADMIN_PASSWORD: AgCc3aOdHM4xN75bmCbiizkhvqEi+Fz8JwLa0i2lgA/xHk9VI3fBVT11lxPcc/9y5FpYaCd4D65Z1XHw/0wijMy0rnWX3pRw7m7Q/kOA3BpfG8rCLO08jNP/SAi9GQ0AzQN51tjLkhEu3kzVP9MO63yPLyQ+LEmbfM7bHUx9DKm2UZiulG11Kwrpf+FTwU7tdCcJqzcO2/U7pc1PpX5V0NYbjy/5m6VRQiHEWlTjnogU6MNeLjOg96FbDELa9NguzXmgYwTHKN89QIXIeRztpz14OXQAvz/7QFdGIoFj+dXJV7/rUC2W0Qb9Arg8+Wrs4piioUuUWnPvOhj/qvVrE2H7em+OhbRKaaLJTPinteOSOt5MVNesM69Gkj59Z+wwTLqgXICUx4AgRaEBXhNiu6MbAz5DJSL75TrH/mt30/sVCmV9ETqEWNrm8hKFdNJnxzzqj9dfbc7mVjNA3N0MbarjD+oCoyX7KYejPCxrpzWOxbpUz6bniVqKoADYDtSkYCWKypNxsj331hLa3eP4v6iYKqOExiWyh+5NHRuqbvQ6mwtWsItSJt2GHQmIYCpSkbDG00Uq1gbYGz4cLhRHyXM78/b1glUhYAzUEQHBBrwreqbBFuYZ7IbQritUsB470v56MWDRl4fgYAAW6NNJjY/bfDj/zMsIfKQLjuz+9FIOArMKp/ThgsEhS72WV23ldRXLChnJX1UExX/EeQbjP7M=
  template:
    metadata:
      name: monitoring-secrets
      namespace: algosu
