---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-secret
  namespace: algosu
spec:
  encryptedData:
    root-password: AgCGZUWBOWeHVDZ4IrNtAQs+blSqmFHemTl/zGm3ShM83GZlNL59jGu+sqFU96nIJSWGyzhJCbijzJ6e1NfGGya6C93P/QXOKMiYOGKrgOsfjzVKzdW5nWiFOLf8K9QTfjwHi3bNfNWf/R9+B6g4pUqpSucLPLkKOqCeoYA0eKzUzlNMBkrcH2Qd/tTn72JUDaGrAJbhCpbCyAj0Yk5RvOrNRttURUOs0mFA8ds5FIzvxlIyKhbCw7CoqIYeqVAYvE/2xX7Me+wRObKnoEkZG+g47G+Sg+T6z9g1JT9KZPNwzckpAfZi8GRLrZTaxv8DEnwoKX43xoWitki+n8gHfReE8b+38btIVHAfXQEGsnyZ0w9W9NsB2wf9D5NCWZ/vYCoCz/g3rDlroB5OGisdyT0TbZSu/IgHatmmphMg8W9MRk5m22iRI8G5V/hiTFo2N5qoGkJ39b/p6Hwb7EDLgayy6H1e/Kg8t3WmgNdA4nIlt7kiNvDB30frfbs4vQYKnZCIBghmlTM9k9u/SUy8NJAx12D7MlIb++XHtmFHLYQrUvTznc6ndi3vD18DV7Npz2iwoKxOFYOwdfj2o5Hj87w8Q2eyVlEDMB5sJv/YJgIS7oWjLzyZzXDy0tlAVPmclZVUIiaizETgThX2dq4LN38ug5RXQL+Yl4Y1bXL2s4+nxvGvW/5FBJaDhRAe63Ycg5xnzXcU8kzlk6j5tWP1WGs=
    root-user: AgAnZyq2/cBN7wB+8U5PI/5hYyyzVl5mBebaSguEur6Vb7SQtL5IV1gCbZAXY+QEzk+kqY6Xhgs4D3tI8pok3Z77a3QhHZzntZwtQhvEQHHDvLVx0Ziv5ydJBTig3x506mPddq+NC0vRFsB8qxn6Ou4PhYpzV0oljoM9vw5ZvZZrVCfJ+wM9WPqPxADkT7tDSeCTffvlPS1wWliadc8s9LJ13XA3y/8S0BJApfgc5j3bubNWG260Uv50VDIqf8Wj890mVZ3t/gxSe24F6UpUFTwREB9XLPOrtQubb5k8+zaYCD7Y8vFoyW/jKYnSfztDaeMqStPCYkBbYG8WRbtc2wHcTLrUy3WhZhLVUTMvG4ch9iaovVsKjU0xuWd3wsauT3/Hlj8Kpbtwz5WLg6VXAqLzIaY4zjnBL2kvtNgufw3DqQGbHdsgG4hYNSEBENQQBG6OrrfXAK9hh48V7D+7u/umXvfNZpMldgv+qOYTZxfP/rahJyBJrsWK1uzho7H6h4Z3r2DxHaErF4NybbAWEiu17/ZLdbdPnq6yeXDJSMu+slo6A6IEJ3KZPwgoGBv0LOXBWH25E5aui0FgCod0WQxIPN4Tw+aOyq6JZHdx73O9Nyt1ijb6bWyqwPAl5J0rddGl8zHZE/rSh1j+vY24LuedDOVhrMpNCCdNa2PfzMD9Zlo1bEu9q7FnsOaBaqElqstmYfUQ7eL5hw==
  template:
    metadata:
      name: postgres-secret
      namespace: algosu
    type: Opaque
