---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-secret
  namespace: algosu
spec:
  encryptedData:
    password: AgBD/b7crwvGKvsRJ1oMfEIvPybi2PDQ9DqJm5vg91qEwykDpzPNFvSaKGaKaouJYD0aCjlGAL9na2D5EpK5VWhGRxKQY453ddmwod1AxneWa3jxA6T87dOH7uHna2RTh+G4tjQR9gchLRvm/XvPYsBbCKe3qGylX6Jgqj3JP9hlzxFgRvw89divUrO+1fX3Jowgh3ICK8sbIG6HEZjSV8OatvON0q2RmNF7calfnePIBE57hIb18UK7hq0tzjki0/YOwAWj8ClFDsSmVj/Z8j+zTFFJR+e3FPI+uZuOBQBX4+0kvYqlO+HtftZCejn93A10BIbYnAOmxWQBqntWABlgrZzWDxhX9mbCZhG7jkOdcneizEtVlN9Or97ERjoakire+7JBPQ8qUXYnZl0ao88uXC0brrJ5SFhXtVmh07Phy7/cPb94HMvx6KILd/iXoXNd6OI0zQyua2C4cFecs3XpxYIkzdkB16YtifbCPo3D33W2PrMI5slnfraBpXFDuH7Bjr4aophzM/6lvFEptBU67MZt4wLr+4qM++ULQSmWgBYKPOIlkk1GGKtTbimGgGnkOXYMJnRqsdujYgbmYHqBdZMJebssRgcNijroaiL37xp1KuoNAzCaqWK+A73cE6RiJOFTrtez4j0R/CWY8psNU4p97dxhb5Y7DRyUX69HVdxxmxth9co8bIHT02nls8Qy78UhbNNreC53yoJoQcWd
  template:
    metadata:
      name: redis-secret
      namespace: algosu
    type: Opaque
