---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-secret
  namespace: algosu
spec:
  encryptedData:
    root-password: AgAK/qolRYn9qTl8Vi+MKK9sn4mNF+IrAk2GLkEaq9IQbiHhPD7kXInN+MZxV+3sNSmTaXLrwZAuk72LhRiJyh51EpWkQIE2tuSNvt1K+4l9zQ0jakFbhxiOUtgVx6+FGSlQ4eZIxn5X7YWp+9nlE0kkSuWX6Eq+yapQV97lQ3QyUCh97sDBdjRNXnYSKFngcKu4g306FPGyxU5vE/xZA+q1cOAf+q1eOAb2PN0N2r7iSQu6dZ1Mcw+LLE7g2DVBF5zIg5tq2kFdLz5AXNpg8E3Vb3eDaB17VSbjxmtiWnNYlRT6uIn5IIO4kIh3/MbiBGMR/bRYj0ff1UTn5Jn4tBTRAIPlSZsx2mPxr8LJC9MiOCDOr5ifimscWJjtGlcc+fI5SPRNkaul970xj7b9Q5FnycsPBaQF579HBbZRmyfgDo0F2l85+vRJLQRJbux7EBXaP379Sqz/GUSs2Ejdsgx5H8vfyCKy8pd7q1Nyc13dgkkR+kYa8bLwwxNKZSjxvltcOmmiZQ7d/7dzFezIW4yfpWSOIUvzF4nC+9bLiB43/qhZ/QsxC7ifBa229WF2ceOEEq+EnmSQu1qIOVP+1oXxc9Ft8uWMTYJwt0KT9v7CHgFOkgn5r3L7KbvrczjbPbvhctQH7UpSrVvCn/XlxZG9je5KtDzp6t1n5sANl4NXjT4wH12Ku18fDLw1lie36BsOnzEVrNG3LnrbGby1Y+yc7A==
    root-user: AgBFSSD4eGMBecyiFHFWM5gt3CEKpMO2A/8j1p8eaQ8h3F5puaUjNxi3Pp6Ra96bjTZH8cPm6vt905+7Xkfk9V9259Z7dCcIXoAK3ZoAHCUT5B/IhZdhGEMBbdZ8FCNlqrPKQWrj3d2aGZ3jY+PUgrd+hKmvu3KIDniHtk5ZYkyH6XcEqMf4MDr9ekQAH1LB6pi6rTXgnDGxyh3ULLAQ/2jHoFh1S1/lMNdpfBE5VVMxJOjzT2BHa74IipwnQwcJ1NA7jT69w94W2+UMeZLD/FVBhSuTQ17lZ5JiSJPmc9jk9toGL2dEAV/c4WZrbqWyxEFPCjXeLtWyewCil5KuW9xsfvxiaZrPCRZLKQVlB6qV0JiucLq/ORvaPRz/F3XYbDrlxWlnSq4pMyPeb8eSOY6JL53vpT8X3HQhyHlkYnmf+aOLCvbTBVBL2nkBGqW4nEjUdL4m/FfshtWUfi5TN0AwuroyEjlGOI54s/hyzF8B/2hVFHNZgIldqh++exsvBGN//7wjs1rucZvnz4ku5tLKp3LYj8LU7qIpTN1kjU+/VigUIIY8CAmQfA+fpNOGtE7AT4Ews8RqyDZJT9ggubx5lPMQp+TrsVgdMoMFl2jBhivnYe5ypp8jky/7K92n+JYCQAT41Anvd0ABGqAKIfSmtuSKsmZnhZvLSBcU5+IzaVY3RCkKMU9X5fEOS1723BL2scgu7fJYQ3SHXg==
  template:
    metadata:
      name: postgres-secret
      namespace: algosu
