---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rabbitmq-secret
  namespace: algosu
spec:
  encryptedData:
    password: AgBgActn1v8xDa+rHPCxPMS/lnD1NicEBGZmqx25E6VmjwoOlllTafk71nfmi8MiEBctuwfczgtEZa4bsDgvNlkHUgqSkuml0YtGz2FYB9diTfk+Ya5ZQrZQXaEsmRFpAYQxfanDRKEgDKp5xG/b5iWTAU6DT2M3Li6SCLqe6cmsHKdRjsT1BNLwQtbb8MQFqEVOCJk5oIfHsZyiQBYqwdEbHlnrFbep8DHS279NGwueQU212YXPChz5iqEhbsC5P7p18f/83RgImcMFppRrhTVKBPmXm8Zmao6M6GGuu+Z98lOnJ7sCDchs4psFMvwbaW2zwAJNsHb41Wjsn0utVe5E/k86V+5Z5CK1JRrulhK1c+sYLiz4QjWXeL6FCsf6iJOzYxaBrzMBzDZxgpEeu4eZEB0lWelJH+I+JgOalWnXb0g75fe+3zxcH5Y1/SQX/8X3wx406bMUjM3w3LtBfTB5PKcQN/vljXSsaHyLO0ceNbFzmvCkIzey+MDLdQsTaGODCpBOVRQdj4oW+oWDyl9ncUpQdUb1VB/AvN8ZhRdQvhyFX0vogmjo4d9t5ErQ95PQpOufuIYIZPgSz7O4KJi6E8P6SQymYVmB3CbfLU8SRI/+iTc1u+/RWi+OY4LCE6RsaO5XQJQZBYE4jyAr+aWYT1+OnFj4x//+urYT5eQ+i/iiQzE/8OY2IXtKIriLDghpIoNYZ8e53fpn/BBkKA==
    user: AgCcQEImwqaqjBCKsdaHqZaNXKidU6Y74oONrprH8VbawOxP5FqeJBa2m1B4nTxK7/d6cNi6IOBLUcVlra1tTLSDrML2z17yN9nOv7IsATGbv6QDq3xMCfG0DEP0zZ6VTMvVn4ltiCmKPZvruezofc0P7vzXBBFqx+iShUfKqsPdBoe6AXXU0tDFNaTYgn+vMzcIxh4nG4qKtw1ohCkWjdK31oI4z8hcsO48lYCJD/jJUm4hfVeafxnJ1HHFRnmjZ2G0N6bUiGrSXaKk17EVWzuc5X17ixKVWuve480O1502C6Z924u6WFvRE69n1rN1o09Vq1AD3fKFZYCxPA37KP2DW4/ollvr+0trjzQxRsJMlGBWxlMcpeWFKMCht/00z54a+z8EZS0ksVbECOZmVmmC2LeJgLqegHTMlgcbchuS3zqS+vG/ygLESuMzmsKS64uNprPfnFHxT+mjk508UoIDv8sSUqJxwRxub/CD4CutWjlJ8g6GBnFA4U0I+tpbQI2aHPQoih+0j/6eSJH+jL84ZkdL5QxqQ5eRiwYly/Jf5GFxyniy1aBPQOCenw9ZnxjUojbQK9Hc0Xb+OTg9qS5n4qyOADamYv/GoTWkWQ4pJ/wuNFwBHG8DFQsM0PMlKphCgoIF7Cwi0r0kOmnb1rTZULTt3lvtxnVRhca7qCxT1JaVqSGwUL+h3fFApo6lKRj63IOaH4c=
  template:
    metadata:
      name: rabbitmq-secret
      namespace: algosu
    type: Opaque
