---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: monitoring-secrets
  namespace: algosu
spec:
  encryptedData:
    GRAFANA_ADMIN_PASSWORD: AgDhnTtR3WC2WOLmpDRwhQr1WxuYZRcZSgrM36tQ8i2KW0Y854nkJIifmF9IKMUvD25naNCzlhU+pI6fogCIX7EMqileprerY9XXcPLBlC7PtJCy4gT5h7AxJNu1NUx0wBJ3Mas8j5TIxLw1U9k9ylyHMp7tSbvpgaxQb8ZOauNpJDA3U9MUFRh9bY1bENWCXgsQyXFpNxRAZgAQwC7WiQOjIdBdkTrhEfTAWsRhQs42ZZ8ftK83+w0hUrfIRkOtplJGmuIzkqCcOETf3KCSFs0SBGgd30WIc1RA4u+Us9SsxXeN90SgaZJgHq5NUWWhEJv76e70MHMfGQOYx/9/aXQaeYjE/irGpBJevog10WsVFGBMLdDzBNWdjNtwaDQ8s9hmJqEeoouvcnhUERXvb9QjczLYlD8oGfYYWdu6ZooabhowrgMIHSlMvjxXweU58AC9vPfL9R7fEEnl8IxtK1RjxevLrGf8o7+khC/kfENSadnVco281nR1iIMCrgdmWMmDcSDGe9CBEP0nfOmwAfJDwgZ1bbAgStLssvu7re9KmKXSPe6Ex7OTVAeVYxe47ibreWt3EMiAv/XPyH3TxBaBuraPaC/fdL1sndDgDgBx4+nbcUoe2cPmQ3wUbTwzPav7PE3ucz9Wbqldx0fiJp9uh/g83+JJHU8WHgxu3rpPyqeF8hr/2UhrkBTH8ZpYvAXTb9M2GKkqlJJS2015NxqIIEPx9RR1Eq8wZQZ8U2TuAA==
  template:
    metadata:
      name: monitoring-secrets
      namespace: algosu
