---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: monitoring-secrets
  namespace: algosu
spec:
  encryptedData:
    GRAFANA_ADMIN_PASSWORD: AgAz2m6K2VY4dGL173SrcmeoqaEYZhOWH4ItxlGg5AJgLtx2tN5+tINz62fjKjDz/L64ZIWDANlt8zTJQBhdGk9rNvaLJ/UJcDOxU0xYQc09JtBPwktZYzuE2RuIvjkmyYCQpMNYOAdNuvueSrJ9uqH1taEwzdBEPqFSdFy559A7khDKUTe3f/a49vNMr7URzOLLqvjCj8Xwvp801cQX9HYyAa9oWqQct6tLtVABg6BMQkNzf5iFCso9dOzyZ+CwIS0Zu4v8abBLrwnN9wmuc/yytOkYnYvY7oPcDEQAujAqlnNNiBjNOq4OM3Z+gt+lAZEF743yOAsosnASdETCiPaoR1LkeZXSSIEwHJLBPA3WKX5fplOYyTcEB/uRFydhRZFURzfzQPLuI2mDvxCK4oQRFkyui7C8B9sAA4IEmPS3UTh75BEZo4+vCQuTcryxBaSm+CGrJU6+3DUdIK4KHD4oXTsfY8xiJqbyOeqr2KabSvnHrFX+Etg7+0ulfSIBt+Zz3MUDfToDlOkD931wwhb0SJGUz1n0bj+AnVVBHcreds455AJEIdwGaeyI/NBolmy9S50rZdi0oTPG2Bgl2rzPZ1vqQ66/E1II6Ou69/Iy/xMY/ZCAr6aoNxQYbx3nG9E5JZ7nGp6MrUFq+nDIjC1rE1Eke5Q6bX8qjWUcjw5+XgMa2GXR45+zihzxHxl5JkWV+Rgjq0o0QL0=
  template:
    metadata:
      name: monitoring-secrets
      namespace: algosu
    type: Opaque
