---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rabbitmq-secret
  namespace: algosu
spec:
  encryptedData:
    password: AgBJHQd04XNYd1lWuEik4WLoWHzO6G4Nq7Sp6V/73HqZKin4At09wrfIdFYPs4HrqRCeQwFAl9F5TuX+8Y7SX9bDWSK0O520lTHTdiW61+JMyAvmUQJXEfy5MSkQ2sAVo9zMewpEJJvQhYDcHs2WQ3nrTtm1Bx355NScYbscROnsq2/hMMPYqglbk8cZLYSwQSV6Nae8b7RpmUjSw/aJnKxY1VoqiDY/EPc5Yipdpdd8jssk/58GlGzQ9yF2n9utPK9DGTYqSaO/jfrn39wJ5hUsLHtnN1C1awwmpKzfb3mOyoRo1H1xjdRrRmx8kSXPJhSlmDMi15QkrqE1xE7zRLW1B89X9X4b/QPoM+JTQnA4bsEIGLGHNWfsOsI03L/IUYCmt51/uyvqRghxN21+QwB7VViLGVdpNVPK69q0+QKiyoSZ0yoAOzpYKs4LjhNDTgnLLAYJdj5MV5LZfcEoPFdLV5/nuZPzmZixIAv+sEO5U2plTURjjL/NpD4MkxiZzbwX4HnYZy4/qwUNZQCTGB2Tdzs5kX5N45VXikSOTH6wj/2Kqfx2PaAebOloabEOmTcvOtMrWmaoZ7q6hGQYrGWGtRTUPHw4UaWhujozY981P17ToElSPFDN0HByVK172I+tTnUK1VE2ImMWv26uVdbDbfoaV5Mldf5q32wqv3xKUYjcr+k2GGP8MKunUNlx2ia6ZZzADCi9cbtsTvK9/c4YrLTei3Mbof16Y0HIIZd4LdiUzXxeplVOrXmERUNn7+c=
    user: AgCdvUwLWwO1fYLuEq3TZKhiNOuvHvRs7thewrNKRZFCteEjS/zGI/b620/3b/0Ls7IhrOZF6+QrN2/VeQ/XnNjOHMay8XyAkfeT4ed0CjNhsIEsHzgPe+8leGdLI4ZnTufAwqIYZJkg75iFvLcH6Ff13v6/1WCdT8W+sUcpf9pyutMu1H9vpzyzzOX43fpV6jI3bgwPa1Wr9pioRJMOLJBzfIyjTZC9MsOpUTeyd4MgeLYQyhbRlycBjdxhtdXbdulCSRbP0HUKMh2H3nj2Te2egCOSy9MyomwJ32D5M5hZtl6ytPUDzulVd096YkU7Q8OcI451skbebsBFrLgja+fCdudWZ7lrsUorvf+iq8vy0e/nXpZwf9O+Mkob4clcnX3ElH4ICE00jQ2iQ+k65DHtT/oiVRJ5Y/vlVvEJ96jFncoA1CtQZrSr51PrfVtTYHxagfYS4Mmzgz10XtMZz/Co7PV8M4nAaOeKWgjkhv1nCxjwrNX2d1n9sd32h/gW7LlOqfBTjzKVpHzHq95Pu7Wbzct1kpneaxnMNBKPTJC46C4iKikpUABJnVmcX+Qno+2jjtvkg8ZxpL2yh4opF3uXmzERzFX+AThxSOHmsuyQIZsF/dJS8ooLgdDXiIV0p2l0cMOCfMcvAOOr6+C2e41SQkLr42S7ZF7DqQeIIc50MD6CWo6Wrqkg6Sb9bOlhgEP9Wa0gUVU=
  template:
    metadata:
      name: rabbitmq-secret
      namespace: algosu
