---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-secret
  namespace: algosu
spec:
  encryptedData:
    password: AgAulbIHt7oOPCPniSU8FYdgdLky8VP7PHrJTRULocYKZg9k/BzD+ukEa2FUY/T3cLsJr06tt+290MXVwMtT8/g90iq2J6uc5Rg1dsM9BUWxnWGp773KTFyHJl6xtzMAcKsBn+43fbRjp1pJ3tutQgW+CH5qwataNr6jhwrvkj9gnl49bHoHvbMtoCoom00a+L0TXj7/YHKsCfMeUKLnR+QgfHgWzctbJ+j76aIsQPoqBn/VUjgl4X6Vv3vBc+rQhl9oceG0ENEwbZC/bxyAWAHFTofI5V5XTM/0d53Yr1btElN8vFUYIIVCpiQYZt1l1s/2LpSrMUR6YPQXNS7mlvNzF8iHV4noQKuzwTTVEPtFF4B7y1E2hH9Luq7bdTcGmICKLOeUwD3/p4nDXWTk5FXF097dnfeX+KsHe7mUXK7I63Kvb5Z1wQEBeH9XmBZeUiX0K+mWw2s3+FzgXons5zGp1TUG/Wo4PpEt3AgcxaNXqBc2A5RQ8kIkXEXl+m1ub/ABCi7z/OjOE/3u6OEHKJxahJNvRvzWiTQxT99Lj84um2QMd9REVhLMX/H1QUUhhE1usrvE162lUkeAmtANi++3u8yw8hXGBF9u37fW5sFYAk4mDOM65AxqIKqgGKaMdO4w7xP9r5Bk63L9cxFW3vR8tLM0vDBVH9qfBJ2NJhSt00n22QL392mcilPIsI0zJ24pq1GR4fy7VL4tpwCORtlhariD4Utx0+xkrCVlLuadewtNkmV9ud69oOT20zstzeI=
  template:
    metadata:
      name: redis-secret
      namespace: algosu
