---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-secret
  namespace: algosu
spec:
  encryptedData:
    root-password: AgBPg3qXg/hf7tuqzsnVuaxFzgpaeNyxDWQIblyqhI5ak5mazLEtCs9bounusYDIm1iY6p3SSkT7rHffwO/6NOgBp2qMSDzHfiHfKR8sWEyHuzUwsDIGEN8JK5TbqLFf2GQhGAVimuWeJQSZ3w/d1juR77WNzGB3UiRfWL6PTygr12n/QcDVWz1tr4mXOLjcs79eTKieqD+ySq6ZkvWAeRTVl/06333A5Bp+3XEYWvQPxNTL/vRphBTkbgQVBHwotKHuoBuaV+4zfTBuhoMF6IFEX2MwvseNaAYlWJPvJRa2Ipf4+OUBpQpLyUInUWZ1jNsdoaKzHqLdyT/FWEF4hx8rwA2hS/KfDhSvq9hk0FAx/Yv/Pifk5Pl9jDw0G1pyAelJiRd314RMVZV0HPQfwkJL4Inw1SvrKsZSBKHu3JUm5nvqvHfYwjfZUi950XqxOlKPYhcyVF4lpxky9KKYhZ3FdQbcEKG1AUrts2JHqQ5v2Y/0/6NymrWOYkJ6HesX2CjTWpQbqqzn/Yl69JKN7Xrqt6tbbZULuavSBwPMb6ATffmI66j86TLmSG+ER/EdrDrBgoZDxToGenVLlxwU3ylf1bycdTo68on1Ez0NBwvc3LwMHYwira67qp7r3tzM5R3JDt6v/pfBqThw+F0/yj9bo60d2kjB28HnWJYGi6vt/Flsdmf0lVNxmJnGkozd60NP+CjBeOy53+9qbDtSNWyFnfQj9mbQq2nkM+lLd7ulzYoh7R0+O3KBJ2Mbmw==
    root-user: AgBeicMqywMeJxb5jQw0UZJryqtjZlSKktRtX42YmUHYXXkMIc9om4iGijCewKHZzdTxu/H5OectEfsz/GUP9sJiHXgg+sz1ylN+hHwuWSx4Qo6XtxrQxAQ4e9n8Jv8fKxrPfyc4YTajImo4Xga8o6f8aH4AEIA0AtIPF7M9NOrppC3qL7JOrdlCq/BaWFeqqCFPbifkVrUUk4+urUtrOH2OkKnUkwrTaieLxQuuCAAfFSZkkWQr2yv3c9gCRyxlaT3AmIQYne3mDtogAkYQZOOQqh7LyyjDz7eQGMxrviZOuxvUNTVs+ENXQS+u/WXE2HE267KOP0LWgYBK0N8IkW6UzoxDuIshVOSGYNKGVAY2MVAfIeUOG/932GXQFuSKKTh1ZqronZJShfmyl3Vrn68Rza6kdAbXjI21h9oPgkpAoEMvOx3HfKk03b5s886kZzX+whco8eiqfruju4oys5IMTKDhOVf+seEU5zUXSaBcUQVTshl/zw2LLiCWMchxERMvIcohCrmcM19CO7bKldtSsnkga99KVZwV2K+aPzhwURFoDolEkHbOSHESC3xppWp4FWDjPbvRy1WCMYB+YxHO7f4NeLGB3ZanUjZNbQbt5vGp8ThdGh9AK+K94xSOEFaeQB5XnshUx66eEMSlOJ6pm5lr6AajTZrR2G/iKD0ZKrRLHsMe+vALuTUUQJLjREMX3bdfj844zKfh1J8=
  template:
    metadata:
      name: minio-secret
      namespace: algosu
