---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-secret
  namespace: algosu
spec:
  encryptedData:
    password: AgCNcVi+YH1q9/isA1+u8lyNGr64ac6W+x0ftL8kW+UMbGOaiNbaWlFp0gpeGq0x0SdY/izgH60P/pwtOgUXqEPjgw5p8bl/XN76Z4mdUI8mbKO/36nhnoBzuYqde5ZNWaLRNVxCVVJ/fRdcSsHEgZDdVrJzBWVcxULlyAal4BPWSt+gHhZ64X+kKVRr3cdO+VsNXFsGhZJw7zLfM9VaGGopJSZ9dcCOr8LHhfcyjdPr/W5x3pdN90MfWVRd62XzT2LoPzCRYz22F4M6osDCmmLba2JdE0hPoaiLJT34qVwhRrHlWrt+23KQYXzIEad7yvL0LwAZfM9gnuKPLPsJESkT9JsHM46RzAchWw/I5HmOQR7k/tm0YlBw8SJgMNMJhFuTJI5pK8kQvmlsVGRSWJviwo45rcODZeEKAbDBmMhvQm1p5rFFX/zE5WTTlU4EJt6+YFeuEbBs2snHWzCT9y/N7kIYz2HX+IpZ3jkQSbMRlIY0zHNDvPEm9DUnF6HR/rjQo14gT/vpnEtAmCrSzUCGnbwujCCvyZu0y7mvIDNP6gT1XijV9VZ4Ow0X6pkd1lA1RnS/o6I24tOS0q2aFV3Ia/Dgu2GEqaCsssRL9GNwvtdkMlQINCn4cK9f+SsQ6RTpTNke76AJUEtlz4TCEZTS32LeYFvjABDTtVz4cbl5w7NUw89+D6BZ9bjXAyk3BXwYh6Tts0k35YotbDQc3yG7/K0=
  template:
    metadata:
      name: redis-secret
      namespace: algosu
