---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-problem-secret
  namespace: algosu
spec:
  encryptedData:
    password: AgBATLuYQ836ie/WkjHtoKzyuHHUxAkfJC5gVL2ejuoRe8fei85HY2fN5zVExollkpb/4OTN95U7wP42zUEsfY40ihtdhSDNXyElAHEVD5uAlT2SvnXcZXZ9J24LCZC0wzBcvcuFqb0OZofQKwyrJ417L7OXxbfjmBGbAMuRZgejCHkgcpVqGQUQwy43rUyT8wvUo5Md1DLtVjNySErHHG7VYGcUbHYEsmGKP0DSLTLQZA4VA4yBV0BJqSYKTiBIQ7QyIAFcDhMlEzU1ZgtK8dqumawFBGXjCk1UuuWyNZoSGwlHCrkbgZ/CD2JRbedkbrdUEqs/5hOTinmw7PiuYiOZJPRWRbSeWP5qVj2xaIN3CWQnBvmj90+o6L4iHfpk5vK4v2dMYW4JAUABPQsTBKdATMolkHQI4VlLvgFTbmzALhWQighhSCw15l91hwdFeC8F87yCH7Gq4k31kJtojvVbRGJMscYNje1ZzKsonW9UjKYcxwAcBdaxNZqfXG0lmviRPJnINAfWDF9awks8/gr50b3hHt9V9/UBsTG9RHsmYlmTxu5yHlSX4ZXWQ4kt842m+N3k/Pxer4ZDCMUo8sc0ZMcjcoLHd71BI4btbFKTy2XUuM7WHwuejaFp3b/Y/HeRg/A9kINFLnt/07Qjf74jWNCt2I2JvVL0YMhEY23k46VM/m64LM5cVItXDBVBFIqZIRH8LLLq44GcgIcSSWCv5g9m8inksSKEfNqgkThG/w==
  template:
    metadata:
      name: postgres-problem-secret
      namespace: algosu
