---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rabbitmq-secret
  namespace: algosu
spec:
  encryptedData:
    password: AgAlqJkhlq2cYd2+uLdmO+K8EUBrTgRn9AM+bRbOIr7JGoqw3vxiVZ8PlGCWBlgbjapLGd/EirRGO4V5zYMyQ0Jyg6awLTJpT/3bYAlcDKZ6Ncnlko8vgoKp8TcDinHO7c2uqv57Jw80XtAobkvyCE8aW1DHglp5UtA5d0Ub75nkgxv+O4u1iqi4arlwq1QWlaTs4oyaZ7GNoUYzForaPZ9qckEIxhPJ7wh7fGmh/K/1/6smzcCG5GuzBEzT0EKp804zj//IcIWJ7A4uk8Hripk+ChKzy7MHH0Lw/+tk+JkLJ1pVintv6ZTdjVBL1xfkDtEEvPbU2lRt8dv75QLC04BI/1/GaM7YVofSP5B+lIELBJNqDaXROeY7tJZtQ04IVOmAF3dize8U61sh90P9z/SVQ14m6tTJoqhR7CMljkDdlFDqNpWwuZsb6kkRNO75R/BTEuypnUfaJDz7uBBmM5sVz1A4rlnMfy0ZvL9fmrmC+4Zk8B+9RbjTlda3xSpG9qJWSbUBFiKWBRI4ukjSSqH/1gvyZgxPJLBu9bXCSDouTsM/lAWqzyui1X4VByCdTV7K5Sz25yi0Xn1P94X/TXv6LxP1zNKIaHUDs6YtpbGWU6H2R476+meq72tqeIEVCbzp9CV1eO5yYjGOori8j86Rp8+IMgamDj/HKYsuQKalxng2j4YMh4QcFuoSsE0kU6pbBH2HPkIjamg/MPzyAnA=
    user: AgBaFrG4S/gew8oOxYwvi2UB8gcP8PeLaHlEGQehLHcEmNI5o8rpt3gmKPwLHnmZEtL2ygJJahZptN1o4FoTEbzkDLv4S6ZoITPOh3tHEIUc4Gr1pmrgpUa19PN08OQUlZ7k4ibz3grWms1BNV4kEGUKraarfYinS64tUX1plQHu0de+UU68NAIXX/uWeH/QOFTTu5Ws5HaxSytzGR1Q7v7ajqTDIYWmRChrXiWj6qbozLHP4+QwWW1YoGOjxcmgs9h3zRTwMUzCpmGh8kHZ4iY2QVMl74v6OTda7h6cwtVm9ZQW9++WOjrGRQwfN2+chRUI0dbP9nPm0Oi6YKFDfTeSfdKVbQfu4nEIob3HSfZBje+Z/1lMcTJdamtGoxMOA5tIVGNWSmUMPFBl0SJ1rUzzawD40xNNkUj76zAs3vW26Tn2PNVS9sx2/LGWQiV1Cacpk8bI6/joCGTwVVf1PHtDUvHPtzUOZo1d5ht4/tL5tjoeznvPmfeFqYA/mGk9xzjPAmeUx3ovmAmyC8YfHwAf0JTmPAnulSlxD2afVakyqjvNZtl9fzRwnA54z/akscQxkC9bnRbWB+ri1WgcBLCjr6SbSJ3PTH4UIWD/1MzWSJ08mvcb5/IA/fO36IBHUBXZU3BqHjngaBy8eAEnpgCCWt2i6CIg+q9JIwSQ6VhO3GPsT8DR5cA6Igd+R0bOPZZX/8dWu3c=
  template:
    metadata:
      name: rabbitmq-secret
      namespace: algosu
