---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-secret
  namespace: algosu
spec:
  encryptedData:
    root-password: AgB23GPiiCDsUO3DF27+tNnoGiWtNp0axGry1MTeyBZRI3WaFCdgJLBpipHs4C2fLHh3chMOPB2Cc8O2XJzSgO0hVMrUUkI1TthQJ5nvzlji+/CT84NPEquELscyBbAMMAQdX6vE/EPCG7dW38rAhSMgu/51z54Gv0KMFfvm2I8NqNyAxnDPH1xEMsY/b+G3HQQyE2j2gwoxyaXS8SPMWbSvTHH22+BDJCEinorOiUi97c3w5Lrr4kUatQj2JVtigOOMT8+cv5l5ReIMMWxlsGCk0bhbYPGRcUemK+zPEulAlhbUv6qJjt29V3gjEeo1vPk23+y9axjSYEPdN36/qApjs01s+AgIVBiH7Haazq0gMhP7GOgxhEINCrWcT31meE4iEGUOBY8vYy4skk/6V8NoUUkBskerm70xzsZPPlprmeDF7oRpLLyGv/KX0BrqYqQApIbqt7/r6qDJOQHLuqhhrc/FhVTrjaCX68nIu1nO6mbkkDjUMyan7GLZTVY1rUgGTH7u6G/R0D7xL2xCjy4kYkbhGQkeVVRO8Ng8hzt/1KWfv9Pxm2lR4+1nkJd4KmKM6C/iayJZO8jCzjSfVCCWXN2FF5Ic4bNcQi7rsyDLQwM5ku5h9Ujx8aWxd6nTuvUNh7MWgI2AroYQkDHCR++Z7khj884V5ZYo8L7Lme4IeVJ2SNE8qIjR2N4WxeAPp9H3FQ0NCIIcvrJHJkT5oiTaeC2J3E204KcRZjC8uA9W+g==
    root-user: AgCvehocLFrajFIIbt8RdKAK0j1jDVsvzOSX9rJTIAUCDQ+o+uJjvYiLDnCmf7+bhXKwKq7/cxQ5E1iE5giNZTShsAxOyZReAcHmUSFn2S8+Gm2OKzCJwtepF/FVYAIZNjcLcfhkyIPUNRsupAnYelzWL11SrLpM9u2rYY3mT1DLimYy5I+etewWVcjev5rGZ7bS3EwwE6XAvaylsABUzQlOjj5gazzXTc1tAH+Hmv8xqoYeRFfMTSammXFYT/kirGQw8dVSUYiZuBBxFYuqGsiePpdo/X4vhmKmKX4dJbdPYC5HpeEt+ChrAqvdT2u70Tk51+ChldR+CrdJxXY2uAmEeBMBWz3FSwWMLaiD2WB8qoiGlW0qESI5JeO2D2/SG5QukKKw3i/J/HPQaNDhyvIXI0SWi+f55BzgHiUJaNeYZ2Dm7RTvHGpu6gDyuguL8S0ZVt0BTdSUiYDbM6SYYcxAdwnQX+473UeMzjF2R6Wyo996AJl/L8JtMOkr4z9nEYqjh+c2pWIZ8g02+yB9MfQoRGadm9NOvpCEk7LxmDcUx+9sC/6mliTHICwWgc5S0rEtiKARMAVtrgKQXuF6sWxszcsd2Jbd1rE6ihGlBncyymnJvTczZK9kIOrP16GuXOeeJDESwUeFHW54fKW8Y+1f2TyBvxyd2diwNT3oazZerSNpfHhSR3vY1boS5Iw+uFg0iaDjEOA=
  template:
    metadata:
      name: minio-secret
      namespace: algosu
